server:
  port: 80
  env: dev

mysql:
  host: 127.0.0.1
  port: 7519
  username: root
  password: flat-server-test
  db: flat_server

redis:
  host: 127.0.0.1
  port: 7528
  username:
  password: flat-server-test
  db: 0
  queueDB: flat_server_queue

jwt:
  secret: test
  algorithms: HS256

log:
  pathname: "{{PROJECT_DIR}}/logs"
  filename: "{{DAY_DATE}}"

login:
  wechat:
    web:
      enable: false
      app_id:
      app_secret:
    mobile:
      enable: false
      app_id:
      app_secret:
  github:
    enable: false
    client_id:
    client_secret:
  google:
    enable: false
    client_id:
    client_secret:
    redirect_uri:
  sms:
    enable: false
    force: false
    test_users:
      - phone:
        code:
    # 大陆短信
    chinese_mainland:
      access_id:
      access_secret:
      template_code:
      sign_name:
    # hmt: 中国香港、澳门和台湾地区
    hmt:
      access_id:
      access_secret:
      template_code:
      sign_name:
    # 全球短信
    global:
      access_id:
      access_secret:
      template_code:
      sign_name:

censorship:
  text:
    enable: false
    type: aliCloud
    aliCloud:
      access_id:
      access_secret:
      endpoint:

whiteboard:
  access_key:
  secret_access_key:
  convert_region:

agora:
  app:
    id:
    certificate:
