server:
  port: 80
  env: dev

mysql:
  host: 127.0.0.1
  port: 7519
  username: root
  password: flat-server-test
  db: flat_server

redis:
  host:
  port:
  username:
  password:
  db:
  queueDB:

log:
  pathname: "{{PROJECT_DIR}}/logs"
  filename: "{{DAY_DATE}}"

login:
  sms:
    enable: false
    force: false
    test_users:
      - phone:
        code:
    # 大陆短信
    chinese_mainland:
      access_id:
      access_secret:
      template_code:
      sign_name:
    # hmt: 中国香港、澳门和台湾地区
    hmt:
      access_id:
      access_secret:
      template_code:
      sign_name:
    # 全球短信
    global:
      access_id:
      access_secret:
      template_code:
      sign_name:
