server:
  port: 80
  env: dev

mysql:
  host: 127.0.0.1
  port: 7519
  username: root
  password: flat-server-test
  db: flat_server

login:
  sms:
    enable: false
    force: false
    chinese_mainland:
      access_id:
      access_secret:
      template_code:
      sign_name:
